/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCompanyIdRouteRouteImport } from './routes/_authenticated/$companyId/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthenticatedSplatIndexRouteImport } from './routes/_authenticated/$/index'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as CliAuthIdIndexRouteImport } from './routes/cli-auth/$id/index'
import { Route as InviteTokenIndexRouteImport } from './routes/invite/$token/index'
import { Route as AuthenticatedCompanyIdActivityIndexRouteImport } from './routes/_authenticated/$companyId/activity/index'
import { Route as AuthenticatedCompanyIdAgentsIndexRouteImport } from './routes/_authenticated/$companyId/agents/index'
import { Route as AuthenticatedCompanyIdApprovalsIndexRouteImport } from './routes/_authenticated/$companyId/approvals/index'
import { Route as AuthenticatedCompanyIdArtifactsIndexRouteImport } from './routes/_authenticated/$companyId/artifacts/index'
import { Route as AuthenticatedCompanyIdCompaniesIndexRouteImport } from './routes/_authenticated/$companyId/companies/index'
import { Route as AuthenticatedCompanyIdCostsIndexRouteImport } from './routes/_authenticated/$companyId/costs/index'
import { Route as AuthenticatedCompanyIdDashboardIndexRouteImport } from './routes/_authenticated/$companyId/dashboard/index'
import { Route as AuthenticatedCompanyIdDecisionsIndexRouteImport } from './routes/_authenticated/$companyId/decisions/index'
import { Route as AuthenticatedCompanyIdGoalsIndexRouteImport } from './routes/_authenticated/$companyId/goals/index'
import { Route as AuthenticatedCompanyIdInboxIndexRouteImport } from './routes/_authenticated/$companyId/inbox/index'
import { Route as AuthenticatedCompanyIdProjectsIndexRouteImport } from './routes/_authenticated/$companyId/projects/index'
import { Route as AuthenticatedCompanyIdRoutinesIndexRouteImport } from './routes/_authenticated/$companyId/routines/index'
import { Route as AuthenticatedCompanyIdSearchIndexRouteImport } from './routes/_authenticated/$companyId/search/index'
import { Route as AuthenticatedCompanyIdTasksIndexRouteImport } from './routes/_authenticated/$companyId/tasks/index'
import { Route as AuthenticatedCompanyIdTimelineIndexRouteImport } from './routes/_authenticated/$companyId/timeline/index'
import { Route as AuthenticatedCompanyIdPluginRoutePathSplatIndexRouteImport } from './routes/_authenticated/$companyId/$pluginRoutePath/$/index'
import { Route as AuthenticatedCompanyIdAgentsAgentIdIndexRouteImport } from './routes/_authenticated/$companyId/agents/$agentId/index'
import { Route as AuthenticatedCompanyIdAgentsErrorIndexRouteImport } from './routes/_authenticated/$companyId/agents/error/index'
import { Route as AuthenticatedCompanyIdAgentsIdleIndexRouteImport } from './routes/_authenticated/$companyId/agents/idle/index'
import { Route as AuthenticatedCompanyIdAgentsNewIndexRouteImport } from './routes/_authenticated/$companyId/agents/new/index'
import { Route as AuthenticatedCompanyIdAgentsPausedIndexRouteImport } from './routes/_authenticated/$companyId/agents/paused/index'
import { Route as AuthenticatedCompanyIdApprovalsApprovalIdIndexRouteImport } from './routes/_authenticated/$companyId/approvals/$approvalId/index'
import { Route as AuthenticatedCompanyIdApprovalsAllIndexRouteImport } from './routes/_authenticated/$companyId/approvals/all/index'
import { Route as AuthenticatedCompanyIdCompanyImportIndexRouteImport } from './routes/_authenticated/$companyId/company/import/index'
import { Route as AuthenticatedCompanyIdCompanySettingsIndexRouteImport } from './routes/_authenticated/$companyId/company/settings/index'
import { Route as AuthenticatedCompanyIdDashboardLiveIndexRouteImport } from './routes/_authenticated/$companyId/dashboard/live/index'
import { Route as AuthenticatedCompanyIdGoalsGoalIdIndexRouteImport } from './routes/_authenticated/$companyId/goals/$goalId/index'
import { Route as AuthenticatedCompanyIdInboxAllIndexRouteImport } from './routes/_authenticated/$companyId/inbox/all/index'
import { Route as AuthenticatedCompanyIdInboxBlockedIndexRouteImport } from './routes/_authenticated/$companyId/inbox/blocked/index'
import { Route as AuthenticatedCompanyIdInboxRecentIndexRouteImport } from './routes/_authenticated/$companyId/inbox/recent/index'
import { Route as AuthenticatedCompanyIdInboxRequestsIndexRouteImport } from './routes/_authenticated/$companyId/inbox/requests/index'
import { Route as AuthenticatedCompanyIdInboxUnreadIndexRouteImport } from './routes/_authenticated/$companyId/inbox/unread/index'
import { Route as AuthenticatedCompanyIdProjectsProjectIdIndexRouteImport } from './routes/_authenticated/$companyId/projects/$projectId/index'
import { Route as AuthenticatedCompanyIdRoutinesRoutineIdIndexRouteImport } from './routes/_authenticated/$companyId/routines/$routineId/index'
import { Route as AuthenticatedCompanyIdTasksTaskNumberIndexRouteImport } from './routes/_authenticated/$companyId/tasks/$taskNumber/index'
import { Route as AuthenticatedCompanyIdUUserIdIndexRouteImport } from './routes/_authenticated/$companyId/u/$userId/index'
import { Route as AuthenticatedCompanyIdAgentsAgentIdTabIndexRouteImport } from './routes/_authenticated/$companyId/agents/$agentId/$tab/index'
import { Route as AuthenticatedCompanyIdCompanyExportSplatIndexRouteImport } from './routes/_authenticated/$companyId/company/export/$/index'
import { Route as AuthenticatedCompanyIdCompanySettingsSettingsRoutePathIndexRouteImport } from './routes/_authenticated/$companyId/company/settings/$settingsRoutePath/index'
import { Route as AuthenticatedCompanyIdCompanySettingsInstanceIndexRouteImport } from './routes/_authenticated/$companyId/company/settings/instance/index'
import { Route as AuthenticatedCompanyIdCompanySettingsInvitesIndexRouteImport } from './routes/_authenticated/$companyId/company/settings/invites/index'
import { Route as AuthenticatedCompanyIdCompanySettingsMembersIndexRouteImport } from './routes/_authenticated/$companyId/company/settings/members/index'
import { Route as AuthenticatedCompanyIdCompanySettingsSecretsIndexRouteImport } from './routes/_authenticated/$companyId/company/settings/secrets/index'
import { Route as AuthenticatedCompanyIdProjectsProjectIdBudgetIndexRouteImport } from './routes/_authenticated/$companyId/projects/$projectId/budget/index'
import { Route as AuthenticatedCompanyIdProjectsProjectIdConfigurationIndexRouteImport } from './routes/_authenticated/$companyId/projects/$projectId/configuration/index'
import { Route as AuthenticatedCompanyIdProjectsProjectIdPluginOperationsIndexRouteImport } from './routes/_authenticated/$companyId/projects/$projectId/plugin-operations/index'
import { Route as AuthenticatedCompanyIdProjectsProjectIdTasksIndexRouteImport } from './routes/_authenticated/$companyId/projects/$projectId/tasks/index'
import { Route as AuthenticatedCompanyIdRoutinesRoutineIdSectionIndexRouteImport } from './routes/_authenticated/$companyId/routines/$routineId/$section/index'
import { Route as AuthenticatedCompanyIdAgentsAgentIdRunsRunIdIndexRouteImport } from './routes/_authenticated/$companyId/agents/$agentId/runs/$runId/index'
import { Route as AuthenticatedCompanyIdCompanySettingsInstanceAccessIndexRouteImport } from './routes/_authenticated/$companyId/company/settings/instance/access/index'
import { Route as AuthenticatedCompanyIdCompanySettingsInstanceAdaptersIndexRouteImport } from './routes/_authenticated/$companyId/company/settings/instance/adapters/index'
import { Route as AuthenticatedCompanyIdCompanySettingsInstancePluginsIndexRouteImport } from './routes/_authenticated/$companyId/company/settings/instance/plugins/index'
import { Route as AuthenticatedCompanyIdCompanySettingsInstanceProfileIndexRouteImport } from './routes/_authenticated/$companyId/company/settings/instance/profile/index'
import { Route as AuthenticatedCompanyIdCompanySettingsInstancePluginsPluginIdIndexRouteImport } from './routes/_authenticated/$companyId/company/settings/instance/plugins/$pluginId/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyIdRouteRoute =
  AuthenticatedCompanyIdRouteRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSplatIndexRoute = AuthenticatedSplatIndexRouteImport.update({
  id: '/$/',
  path: '/$/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CliAuthIdIndexRoute = CliAuthIdIndexRouteImport.update({
  id: '/cli-auth/$id/',
  path: '/cli-auth/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenIndexRoute = InviteTokenIndexRouteImport.update({
  id: '/invite/$token/',
  path: '/invite/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompanyIdActivityIndexRoute =
  AuthenticatedCompanyIdActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdAgentsIndexRoute =
  AuthenticatedCompanyIdAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdApprovalsIndexRoute =
  AuthenticatedCompanyIdApprovalsIndexRouteImport.update({
    id: '/approvals/',
    path: '/approvals/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdArtifactsIndexRoute =
  AuthenticatedCompanyIdArtifactsIndexRouteImport.update({
    id: '/artifacts/',
    path: '/artifacts/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdCompaniesIndexRoute =
  AuthenticatedCompanyIdCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdCostsIndexRoute =
  AuthenticatedCompanyIdCostsIndexRouteImport.update({
    id: '/costs/',
    path: '/costs/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdDashboardIndexRoute =
  AuthenticatedCompanyIdDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdDecisionsIndexRoute =
  AuthenticatedCompanyIdDecisionsIndexRouteImport.update({
    id: '/decisions/',
    path: '/decisions/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdGoalsIndexRoute =
  AuthenticatedCompanyIdGoalsIndexRouteImport.update({
    id: '/goals/',
    path: '/goals/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdInboxIndexRoute =
  AuthenticatedCompanyIdInboxIndexRouteImport.update({
    id: '/inbox/',
    path: '/inbox/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdProjectsIndexRoute =
  AuthenticatedCompanyIdProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdRoutinesIndexRoute =
  AuthenticatedCompanyIdRoutinesIndexRouteImport.update({
    id: '/routines/',
    path: '/routines/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdSearchIndexRoute =
  AuthenticatedCompanyIdSearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdTasksIndexRoute =
  AuthenticatedCompanyIdTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdTimelineIndexRoute =
  AuthenticatedCompanyIdTimelineIndexRouteImport.update({
    id: '/timeline/',
    path: '/timeline/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdPluginRoutePathSplatIndexRoute =
  AuthenticatedCompanyIdPluginRoutePathSplatIndexRouteImport.update({
    id: '/$pluginRoutePath/$/',
    path: '/$pluginRoutePath/$/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdAgentsAgentIdIndexRoute =
  AuthenticatedCompanyIdAgentsAgentIdIndexRouteImport.update({
    id: '/agents/$agentId/',
    path: '/agents/$agentId/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdAgentsErrorIndexRoute =
  AuthenticatedCompanyIdAgentsErrorIndexRouteImport.update({
    id: '/agents/error/',
    path: '/agents/error/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdAgentsIdleIndexRoute =
  AuthenticatedCompanyIdAgentsIdleIndexRouteImport.update({
    id: '/agents/idle/',
    path: '/agents/idle/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdAgentsNewIndexRoute =
  AuthenticatedCompanyIdAgentsNewIndexRouteImport.update({
    id: '/agents/new/',
    path: '/agents/new/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdAgentsPausedIndexRoute =
  AuthenticatedCompanyIdAgentsPausedIndexRouteImport.update({
    id: '/agents/paused/',
    path: '/agents/paused/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdApprovalsApprovalIdIndexRoute =
  AuthenticatedCompanyIdApprovalsApprovalIdIndexRouteImport.update({
    id: '/approvals/$approvalId/',
    path: '/approvals/$approvalId/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdApprovalsAllIndexRoute =
  AuthenticatedCompanyIdApprovalsAllIndexRouteImport.update({
    id: '/approvals/all/',
    path: '/approvals/all/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdCompanyImportIndexRoute =
  AuthenticatedCompanyIdCompanyImportIndexRouteImport.update({
    id: '/company/import/',
    path: '/company/import/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdCompanySettingsIndexRoute =
  AuthenticatedCompanyIdCompanySettingsIndexRouteImport.update({
    id: '/company/settings/',
    path: '/company/settings/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdDashboardLiveIndexRoute =
  AuthenticatedCompanyIdDashboardLiveIndexRouteImport.update({
    id: '/dashboard/live/',
    path: '/dashboard/live/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdGoalsGoalIdIndexRoute =
  AuthenticatedCompanyIdGoalsGoalIdIndexRouteImport.update({
    id: '/goals/$goalId/',
    path: '/goals/$goalId/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdInboxAllIndexRoute =
  AuthenticatedCompanyIdInboxAllIndexRouteImport.update({
    id: '/inbox/all/',
    path: '/inbox/all/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdInboxBlockedIndexRoute =
  AuthenticatedCompanyIdInboxBlockedIndexRouteImport.update({
    id: '/inbox/blocked/',
    path: '/inbox/blocked/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdInboxRecentIndexRoute =
  AuthenticatedCompanyIdInboxRecentIndexRouteImport.update({
    id: '/inbox/recent/',
    path: '/inbox/recent/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdInboxRequestsIndexRoute =
  AuthenticatedCompanyIdInboxRequestsIndexRouteImport.update({
    id: '/inbox/requests/',
    path: '/inbox/requests/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdInboxUnreadIndexRoute =
  AuthenticatedCompanyIdInboxUnreadIndexRouteImport.update({
    id: '/inbox/unread/',
    path: '/inbox/unread/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdProjectsProjectIdIndexRoute =
  AuthenticatedCompanyIdProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdRoutinesRoutineIdIndexRoute =
  AuthenticatedCompanyIdRoutinesRoutineIdIndexRouteImport.update({
    id: '/routines/$routineId/',
    path: '/routines/$routineId/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdTasksTaskNumberIndexRoute =
  AuthenticatedCompanyIdTasksTaskNumberIndexRouteImport.update({
    id: '/tasks/$taskNumber/',
    path: '/tasks/$taskNumber/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdUUserIdIndexRoute =
  AuthenticatedCompanyIdUUserIdIndexRouteImport.update({
    id: '/u/$userId/',
    path: '/u/$userId/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdAgentsAgentIdTabIndexRoute =
  AuthenticatedCompanyIdAgentsAgentIdTabIndexRouteImport.update({
    id: '/agents/$agentId/$tab/',
    path: '/agents/$agentId/$tab/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdCompanyExportSplatIndexRoute =
  AuthenticatedCompanyIdCompanyExportSplatIndexRouteImport.update({
    id: '/company/export/$/',
    path: '/company/export/$/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdCompanySettingsSettingsRoutePathIndexRoute =
  AuthenticatedCompanyIdCompanySettingsSettingsRoutePathIndexRouteImport.update(
    {
      id: '/company/settings/$settingsRoutePath/',
      path: '/company/settings/$settingsRoutePath/',
      getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
    } as any,
  )
const AuthenticatedCompanyIdCompanySettingsInstanceIndexRoute =
  AuthenticatedCompanyIdCompanySettingsInstanceIndexRouteImport.update({
    id: '/company/settings/instance/',
    path: '/company/settings/instance/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdCompanySettingsInvitesIndexRoute =
  AuthenticatedCompanyIdCompanySettingsInvitesIndexRouteImport.update({
    id: '/company/settings/invites/',
    path: '/company/settings/invites/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdCompanySettingsMembersIndexRoute =
  AuthenticatedCompanyIdCompanySettingsMembersIndexRouteImport.update({
    id: '/company/settings/members/',
    path: '/company/settings/members/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdCompanySettingsSecretsIndexRoute =
  AuthenticatedCompanyIdCompanySettingsSecretsIndexRouteImport.update({
    id: '/company/settings/secrets/',
    path: '/company/settings/secrets/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdProjectsProjectIdBudgetIndexRoute =
  AuthenticatedCompanyIdProjectsProjectIdBudgetIndexRouteImport.update({
    id: '/projects/$projectId/budget/',
    path: '/projects/$projectId/budget/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdProjectsProjectIdConfigurationIndexRoute =
  AuthenticatedCompanyIdProjectsProjectIdConfigurationIndexRouteImport.update({
    id: '/projects/$projectId/configuration/',
    path: '/projects/$projectId/configuration/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdProjectsProjectIdPluginOperationsIndexRoute =
  AuthenticatedCompanyIdProjectsProjectIdPluginOperationsIndexRouteImport.update(
    {
      id: '/projects/$projectId/plugin-operations/',
      path: '/projects/$projectId/plugin-operations/',
      getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
    } as any,
  )
const AuthenticatedCompanyIdProjectsProjectIdTasksIndexRoute =
  AuthenticatedCompanyIdProjectsProjectIdTasksIndexRouteImport.update({
    id: '/projects/$projectId/tasks/',
    path: '/projects/$projectId/tasks/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdRoutinesRoutineIdSectionIndexRoute =
  AuthenticatedCompanyIdRoutinesRoutineIdSectionIndexRouteImport.update({
    id: '/routines/$routineId/$section/',
    path: '/routines/$routineId/$section/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdAgentsAgentIdRunsRunIdIndexRoute =
  AuthenticatedCompanyIdAgentsAgentIdRunsRunIdIndexRouteImport.update({
    id: '/agents/$agentId/runs/$runId/',
    path: '/agents/$agentId/runs/$runId/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdCompanySettingsInstanceAccessIndexRoute =
  AuthenticatedCompanyIdCompanySettingsInstanceAccessIndexRouteImport.update({
    id: '/company/settings/instance/access/',
    path: '/company/settings/instance/access/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdCompanySettingsInstanceAdaptersIndexRoute =
  AuthenticatedCompanyIdCompanySettingsInstanceAdaptersIndexRouteImport.update({
    id: '/company/settings/instance/adapters/',
    path: '/company/settings/instance/adapters/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdCompanySettingsInstancePluginsIndexRoute =
  AuthenticatedCompanyIdCompanySettingsInstancePluginsIndexRouteImport.update({
    id: '/company/settings/instance/plugins/',
    path: '/company/settings/instance/plugins/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdCompanySettingsInstanceProfileIndexRoute =
  AuthenticatedCompanyIdCompanySettingsInstanceProfileIndexRouteImport.update({
    id: '/company/settings/instance/profile/',
    path: '/company/settings/instance/profile/',
    getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
  } as any)
const AuthenticatedCompanyIdCompanySettingsInstancePluginsPluginIdIndexRoute =
  AuthenticatedCompanyIdCompanySettingsInstancePluginsPluginIdIndexRouteImport.update(
    {
      id: '/company/settings/instance/plugins/$pluginId/',
      path: '/company/settings/instance/plugins/$pluginId/',
      getParentRoute: () => AuthenticatedCompanyIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/$companyId': typeof AuthenticatedCompanyIdRouteRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/$/': typeof AuthenticatedSplatIndexRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/cli-auth/$id/': typeof CliAuthIdIndexRoute
  '/invite/$token/': typeof InviteTokenIndexRoute
  '/$companyId/activity/': typeof AuthenticatedCompanyIdActivityIndexRoute
  '/$companyId/agents/': typeof AuthenticatedCompanyIdAgentsIndexRoute
  '/$companyId/approvals/': typeof AuthenticatedCompanyIdApprovalsIndexRoute
  '/$companyId/artifacts/': typeof AuthenticatedCompanyIdArtifactsIndexRoute
  '/$companyId/companies/': typeof AuthenticatedCompanyIdCompaniesIndexRoute
  '/$companyId/costs/': typeof AuthenticatedCompanyIdCostsIndexRoute
  '/$companyId/dashboard/': typeof AuthenticatedCompanyIdDashboardIndexRoute
  '/$companyId/decisions/': typeof AuthenticatedCompanyIdDecisionsIndexRoute
  '/$companyId/goals/': typeof AuthenticatedCompanyIdGoalsIndexRoute
  '/$companyId/inbox/': typeof AuthenticatedCompanyIdInboxIndexRoute
  '/$companyId/projects/': typeof AuthenticatedCompanyIdProjectsIndexRoute
  '/$companyId/routines/': typeof AuthenticatedCompanyIdRoutinesIndexRoute
  '/$companyId/search/': typeof AuthenticatedCompanyIdSearchIndexRoute
  '/$companyId/tasks/': typeof AuthenticatedCompanyIdTasksIndexRoute
  '/$companyId/timeline/': typeof AuthenticatedCompanyIdTimelineIndexRoute
  '/$companyId/$pluginRoutePath/$/': typeof AuthenticatedCompanyIdPluginRoutePathSplatIndexRoute
  '/$companyId/agents/$agentId/': typeof AuthenticatedCompanyIdAgentsAgentIdIndexRoute
  '/$companyId/agents/error/': typeof AuthenticatedCompanyIdAgentsErrorIndexRoute
  '/$companyId/agents/idle/': typeof AuthenticatedCompanyIdAgentsIdleIndexRoute
  '/$companyId/agents/new/': typeof AuthenticatedCompanyIdAgentsNewIndexRoute
  '/$companyId/agents/paused/': typeof AuthenticatedCompanyIdAgentsPausedIndexRoute
  '/$companyId/approvals/$approvalId/': typeof AuthenticatedCompanyIdApprovalsApprovalIdIndexRoute
  '/$companyId/approvals/all/': typeof AuthenticatedCompanyIdApprovalsAllIndexRoute
  '/$companyId/company/import/': typeof AuthenticatedCompanyIdCompanyImportIndexRoute
  '/$companyId/company/settings/': typeof AuthenticatedCompanyIdCompanySettingsIndexRoute
  '/$companyId/dashboard/live/': typeof AuthenticatedCompanyIdDashboardLiveIndexRoute
  '/$companyId/goals/$goalId/': typeof AuthenticatedCompanyIdGoalsGoalIdIndexRoute
  '/$companyId/inbox/all/': typeof AuthenticatedCompanyIdInboxAllIndexRoute
  '/$companyId/inbox/blocked/': typeof AuthenticatedCompanyIdInboxBlockedIndexRoute
  '/$companyId/inbox/recent/': typeof AuthenticatedCompanyIdInboxRecentIndexRoute
  '/$companyId/inbox/requests/': typeof AuthenticatedCompanyIdInboxRequestsIndexRoute
  '/$companyId/inbox/unread/': typeof AuthenticatedCompanyIdInboxUnreadIndexRoute
  '/$companyId/projects/$projectId/': typeof AuthenticatedCompanyIdProjectsProjectIdIndexRoute
  '/$companyId/routines/$routineId/': typeof AuthenticatedCompanyIdRoutinesRoutineIdIndexRoute
  '/$companyId/tasks/$taskNumber/': typeof AuthenticatedCompanyIdTasksTaskNumberIndexRoute
  '/$companyId/u/$userId/': typeof AuthenticatedCompanyIdUUserIdIndexRoute
  '/$companyId/agents/$agentId/$tab/': typeof AuthenticatedCompanyIdAgentsAgentIdTabIndexRoute
  '/$companyId/company/export/$/': typeof AuthenticatedCompanyIdCompanyExportSplatIndexRoute
  '/$companyId/company/settings/$settingsRoutePath/': typeof AuthenticatedCompanyIdCompanySettingsSettingsRoutePathIndexRoute
  '/$companyId/company/settings/instance/': typeof AuthenticatedCompanyIdCompanySettingsInstanceIndexRoute
  '/$companyId/company/settings/invites/': typeof AuthenticatedCompanyIdCompanySettingsInvitesIndexRoute
  '/$companyId/company/settings/members/': typeof AuthenticatedCompanyIdCompanySettingsMembersIndexRoute
  '/$companyId/company/settings/secrets/': typeof AuthenticatedCompanyIdCompanySettingsSecretsIndexRoute
  '/$companyId/projects/$projectId/budget/': typeof AuthenticatedCompanyIdProjectsProjectIdBudgetIndexRoute
  '/$companyId/projects/$projectId/configuration/': typeof AuthenticatedCompanyIdProjectsProjectIdConfigurationIndexRoute
  '/$companyId/projects/$projectId/plugin-operations/': typeof AuthenticatedCompanyIdProjectsProjectIdPluginOperationsIndexRoute
  '/$companyId/projects/$projectId/tasks/': typeof AuthenticatedCompanyIdProjectsProjectIdTasksIndexRoute
  '/$companyId/routines/$routineId/$section/': typeof AuthenticatedCompanyIdRoutinesRoutineIdSectionIndexRoute
  '/$companyId/agents/$agentId/runs/$runId/': typeof AuthenticatedCompanyIdAgentsAgentIdRunsRunIdIndexRoute
  '/$companyId/company/settings/instance/access/': typeof AuthenticatedCompanyIdCompanySettingsInstanceAccessIndexRoute
  '/$companyId/company/settings/instance/adapters/': typeof AuthenticatedCompanyIdCompanySettingsInstanceAdaptersIndexRoute
  '/$companyId/company/settings/instance/plugins/': typeof AuthenticatedCompanyIdCompanySettingsInstancePluginsIndexRoute
  '/$companyId/company/settings/instance/profile/': typeof AuthenticatedCompanyIdCompanySettingsInstanceProfileIndexRoute
  '/$companyId/company/settings/instance/plugins/$pluginId/': typeof AuthenticatedCompanyIdCompanySettingsInstancePluginsPluginIdIndexRoute
}
export interface FileRoutesByTo {
  '/$companyId': typeof AuthenticatedCompanyIdRouteRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/$': typeof AuthenticatedSplatIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/cli-auth/$id': typeof CliAuthIdIndexRoute
  '/invite/$token': typeof InviteTokenIndexRoute
  '/$companyId/activity': typeof AuthenticatedCompanyIdActivityIndexRoute
  '/$companyId/agents': typeof AuthenticatedCompanyIdAgentsIndexRoute
  '/$companyId/approvals': typeof AuthenticatedCompanyIdApprovalsIndexRoute
  '/$companyId/artifacts': typeof AuthenticatedCompanyIdArtifactsIndexRoute
  '/$companyId/companies': typeof AuthenticatedCompanyIdCompaniesIndexRoute
  '/$companyId/costs': typeof AuthenticatedCompanyIdCostsIndexRoute
  '/$companyId/dashboard': typeof AuthenticatedCompanyIdDashboardIndexRoute
  '/$companyId/decisions': typeof AuthenticatedCompanyIdDecisionsIndexRoute
  '/$companyId/goals': typeof AuthenticatedCompanyIdGoalsIndexRoute
  '/$companyId/inbox': typeof AuthenticatedCompanyIdInboxIndexRoute
  '/$companyId/projects': typeof AuthenticatedCompanyIdProjectsIndexRoute
  '/$companyId/routines': typeof AuthenticatedCompanyIdRoutinesIndexRoute
  '/$companyId/search': typeof AuthenticatedCompanyIdSearchIndexRoute
  '/$companyId/tasks': typeof AuthenticatedCompanyIdTasksIndexRoute
  '/$companyId/timeline': typeof AuthenticatedCompanyIdTimelineIndexRoute
  '/$companyId/$pluginRoutePath/$': typeof AuthenticatedCompanyIdPluginRoutePathSplatIndexRoute
  '/$companyId/agents/$agentId': typeof AuthenticatedCompanyIdAgentsAgentIdIndexRoute
  '/$companyId/agents/error': typeof AuthenticatedCompanyIdAgentsErrorIndexRoute
  '/$companyId/agents/idle': typeof AuthenticatedCompanyIdAgentsIdleIndexRoute
  '/$companyId/agents/new': typeof AuthenticatedCompanyIdAgentsNewIndexRoute
  '/$companyId/agents/paused': typeof AuthenticatedCompanyIdAgentsPausedIndexRoute
  '/$companyId/approvals/$approvalId': typeof AuthenticatedCompanyIdApprovalsApprovalIdIndexRoute
  '/$companyId/approvals/all': typeof AuthenticatedCompanyIdApprovalsAllIndexRoute
  '/$companyId/company/import': typeof AuthenticatedCompanyIdCompanyImportIndexRoute
  '/$companyId/company/settings': typeof AuthenticatedCompanyIdCompanySettingsIndexRoute
  '/$companyId/dashboard/live': typeof AuthenticatedCompanyIdDashboardLiveIndexRoute
  '/$companyId/goals/$goalId': typeof AuthenticatedCompanyIdGoalsGoalIdIndexRoute
  '/$companyId/inbox/all': typeof AuthenticatedCompanyIdInboxAllIndexRoute
  '/$companyId/inbox/blocked': typeof AuthenticatedCompanyIdInboxBlockedIndexRoute
  '/$companyId/inbox/recent': typeof AuthenticatedCompanyIdInboxRecentIndexRoute
  '/$companyId/inbox/requests': typeof AuthenticatedCompanyIdInboxRequestsIndexRoute
  '/$companyId/inbox/unread': typeof AuthenticatedCompanyIdInboxUnreadIndexRoute
  '/$companyId/projects/$projectId': typeof AuthenticatedCompanyIdProjectsProjectIdIndexRoute
  '/$companyId/routines/$routineId': typeof AuthenticatedCompanyIdRoutinesRoutineIdIndexRoute
  '/$companyId/tasks/$taskNumber': typeof AuthenticatedCompanyIdTasksTaskNumberIndexRoute
  '/$companyId/u/$userId': typeof AuthenticatedCompanyIdUUserIdIndexRoute
  '/$companyId/agents/$agentId/$tab': typeof AuthenticatedCompanyIdAgentsAgentIdTabIndexRoute
  '/$companyId/company/export/$': typeof AuthenticatedCompanyIdCompanyExportSplatIndexRoute
  '/$companyId/company/settings/$settingsRoutePath': typeof AuthenticatedCompanyIdCompanySettingsSettingsRoutePathIndexRoute
  '/$companyId/company/settings/instance': typeof AuthenticatedCompanyIdCompanySettingsInstanceIndexRoute
  '/$companyId/company/settings/invites': typeof AuthenticatedCompanyIdCompanySettingsInvitesIndexRoute
  '/$companyId/company/settings/members': typeof AuthenticatedCompanyIdCompanySettingsMembersIndexRoute
  '/$companyId/company/settings/secrets': typeof AuthenticatedCompanyIdCompanySettingsSecretsIndexRoute
  '/$companyId/projects/$projectId/budget': typeof AuthenticatedCompanyIdProjectsProjectIdBudgetIndexRoute
  '/$companyId/projects/$projectId/configuration': typeof AuthenticatedCompanyIdProjectsProjectIdConfigurationIndexRoute
  '/$companyId/projects/$projectId/plugin-operations': typeof AuthenticatedCompanyIdProjectsProjectIdPluginOperationsIndexRoute
  '/$companyId/projects/$projectId/tasks': typeof AuthenticatedCompanyIdProjectsProjectIdTasksIndexRoute
  '/$companyId/routines/$routineId/$section': typeof AuthenticatedCompanyIdRoutinesRoutineIdSectionIndexRoute
  '/$companyId/agents/$agentId/runs/$runId': typeof AuthenticatedCompanyIdAgentsAgentIdRunsRunIdIndexRoute
  '/$companyId/company/settings/instance/access': typeof AuthenticatedCompanyIdCompanySettingsInstanceAccessIndexRoute
  '/$companyId/company/settings/instance/adapters': typeof AuthenticatedCompanyIdCompanySettingsInstanceAdaptersIndexRoute
  '/$companyId/company/settings/instance/plugins': typeof AuthenticatedCompanyIdCompanySettingsInstancePluginsIndexRoute
  '/$companyId/company/settings/instance/profile': typeof AuthenticatedCompanyIdCompanySettingsInstanceProfileIndexRoute
  '/$companyId/company/settings/instance/plugins/$pluginId': typeof AuthenticatedCompanyIdCompanySettingsInstancePluginsPluginIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/$companyId': typeof AuthenticatedCompanyIdRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/$/': typeof AuthenticatedSplatIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/cli-auth/$id/': typeof CliAuthIdIndexRoute
  '/invite/$token/': typeof InviteTokenIndexRoute
  '/_authenticated/$companyId/activity/': typeof AuthenticatedCompanyIdActivityIndexRoute
  '/_authenticated/$companyId/agents/': typeof AuthenticatedCompanyIdAgentsIndexRoute
  '/_authenticated/$companyId/approvals/': typeof AuthenticatedCompanyIdApprovalsIndexRoute
  '/_authenticated/$companyId/artifacts/': typeof AuthenticatedCompanyIdArtifactsIndexRoute
  '/_authenticated/$companyId/companies/': typeof AuthenticatedCompanyIdCompaniesIndexRoute
  '/_authenticated/$companyId/costs/': typeof AuthenticatedCompanyIdCostsIndexRoute
  '/_authenticated/$companyId/dashboard/': typeof AuthenticatedCompanyIdDashboardIndexRoute
  '/_authenticated/$companyId/decisions/': typeof AuthenticatedCompanyIdDecisionsIndexRoute
  '/_authenticated/$companyId/goals/': typeof AuthenticatedCompanyIdGoalsIndexRoute
  '/_authenticated/$companyId/inbox/': typeof AuthenticatedCompanyIdInboxIndexRoute
  '/_authenticated/$companyId/projects/': typeof AuthenticatedCompanyIdProjectsIndexRoute
  '/_authenticated/$companyId/routines/': typeof AuthenticatedCompanyIdRoutinesIndexRoute
  '/_authenticated/$companyId/search/': typeof AuthenticatedCompanyIdSearchIndexRoute
  '/_authenticated/$companyId/tasks/': typeof AuthenticatedCompanyIdTasksIndexRoute
  '/_authenticated/$companyId/timeline/': typeof AuthenticatedCompanyIdTimelineIndexRoute
  '/_authenticated/$companyId/$pluginRoutePath/$/': typeof AuthenticatedCompanyIdPluginRoutePathSplatIndexRoute
  '/_authenticated/$companyId/agents/$agentId/': typeof AuthenticatedCompanyIdAgentsAgentIdIndexRoute
  '/_authenticated/$companyId/agents/error/': typeof AuthenticatedCompanyIdAgentsErrorIndexRoute
  '/_authenticated/$companyId/agents/idle/': typeof AuthenticatedCompanyIdAgentsIdleIndexRoute
  '/_authenticated/$companyId/agents/new/': typeof AuthenticatedCompanyIdAgentsNewIndexRoute
  '/_authenticated/$companyId/agents/paused/': typeof AuthenticatedCompanyIdAgentsPausedIndexRoute
  '/_authenticated/$companyId/approvals/$approvalId/': typeof AuthenticatedCompanyIdApprovalsApprovalIdIndexRoute
  '/_authenticated/$companyId/approvals/all/': typeof AuthenticatedCompanyIdApprovalsAllIndexRoute
  '/_authenticated/$companyId/company/import/': typeof AuthenticatedCompanyIdCompanyImportIndexRoute
  '/_authenticated/$companyId/company/settings/': typeof AuthenticatedCompanyIdCompanySettingsIndexRoute
  '/_authenticated/$companyId/dashboard/live/': typeof AuthenticatedCompanyIdDashboardLiveIndexRoute
  '/_authenticated/$companyId/goals/$goalId/': typeof AuthenticatedCompanyIdGoalsGoalIdIndexRoute
  '/_authenticated/$companyId/inbox/all/': typeof AuthenticatedCompanyIdInboxAllIndexRoute
  '/_authenticated/$companyId/inbox/blocked/': typeof AuthenticatedCompanyIdInboxBlockedIndexRoute
  '/_authenticated/$companyId/inbox/recent/': typeof AuthenticatedCompanyIdInboxRecentIndexRoute
  '/_authenticated/$companyId/inbox/requests/': typeof AuthenticatedCompanyIdInboxRequestsIndexRoute
  '/_authenticated/$companyId/inbox/unread/': typeof AuthenticatedCompanyIdInboxUnreadIndexRoute
  '/_authenticated/$companyId/projects/$projectId/': typeof AuthenticatedCompanyIdProjectsProjectIdIndexRoute
  '/_authenticated/$companyId/routines/$routineId/': typeof AuthenticatedCompanyIdRoutinesRoutineIdIndexRoute
  '/_authenticated/$companyId/tasks/$taskNumber/': typeof AuthenticatedCompanyIdTasksTaskNumberIndexRoute
  '/_authenticated/$companyId/u/$userId/': typeof AuthenticatedCompanyIdUUserIdIndexRoute
  '/_authenticated/$companyId/agents/$agentId/$tab/': typeof AuthenticatedCompanyIdAgentsAgentIdTabIndexRoute
  '/_authenticated/$companyId/company/export/$/': typeof AuthenticatedCompanyIdCompanyExportSplatIndexRoute
  '/_authenticated/$companyId/company/settings/$settingsRoutePath/': typeof AuthenticatedCompanyIdCompanySettingsSettingsRoutePathIndexRoute
  '/_authenticated/$companyId/company/settings/instance/': typeof AuthenticatedCompanyIdCompanySettingsInstanceIndexRoute
  '/_authenticated/$companyId/company/settings/invites/': typeof AuthenticatedCompanyIdCompanySettingsInvitesIndexRoute
  '/_authenticated/$companyId/company/settings/members/': typeof AuthenticatedCompanyIdCompanySettingsMembersIndexRoute
  '/_authenticated/$companyId/company/settings/secrets/': typeof AuthenticatedCompanyIdCompanySettingsSecretsIndexRoute
  '/_authenticated/$companyId/projects/$projectId/budget/': typeof AuthenticatedCompanyIdProjectsProjectIdBudgetIndexRoute
  '/_authenticated/$companyId/projects/$projectId/configuration/': typeof AuthenticatedCompanyIdProjectsProjectIdConfigurationIndexRoute
  '/_authenticated/$companyId/projects/$projectId/plugin-operations/': typeof AuthenticatedCompanyIdProjectsProjectIdPluginOperationsIndexRoute
  '/_authenticated/$companyId/projects/$projectId/tasks/': typeof AuthenticatedCompanyIdProjectsProjectIdTasksIndexRoute
  '/_authenticated/$companyId/routines/$routineId/$section/': typeof AuthenticatedCompanyIdRoutinesRoutineIdSectionIndexRoute
  '/_authenticated/$companyId/agents/$agentId/runs/$runId/': typeof AuthenticatedCompanyIdAgentsAgentIdRunsRunIdIndexRoute
  '/_authenticated/$companyId/company/settings/instance/access/': typeof AuthenticatedCompanyIdCompanySettingsInstanceAccessIndexRoute
  '/_authenticated/$companyId/company/settings/instance/adapters/': typeof AuthenticatedCompanyIdCompanySettingsInstanceAdaptersIndexRoute
  '/_authenticated/$companyId/company/settings/instance/plugins/': typeof AuthenticatedCompanyIdCompanySettingsInstancePluginsIndexRoute
  '/_authenticated/$companyId/company/settings/instance/profile/': typeof AuthenticatedCompanyIdCompanySettingsInstanceProfileIndexRoute
  '/_authenticated/$companyId/company/settings/instance/plugins/$pluginId/': typeof AuthenticatedCompanyIdCompanySettingsInstancePluginsPluginIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$companyId'
    | '/auth/'
    | '/$/'
    | '/onboarding/'
    | '/cli-auth/$id/'
    | '/invite/$token/'
    | '/$companyId/activity/'
    | '/$companyId/agents/'
    | '/$companyId/approvals/'
    | '/$companyId/artifacts/'
    | '/$companyId/companies/'
    | '/$companyId/costs/'
    | '/$companyId/dashboard/'
    | '/$companyId/decisions/'
    | '/$companyId/goals/'
    | '/$companyId/inbox/'
    | '/$companyId/projects/'
    | '/$companyId/routines/'
    | '/$companyId/search/'
    | '/$companyId/tasks/'
    | '/$companyId/timeline/'
    | '/$companyId/$pluginRoutePath/$/'
    | '/$companyId/agents/$agentId/'
    | '/$companyId/agents/error/'
    | '/$companyId/agents/idle/'
    | '/$companyId/agents/new/'
    | '/$companyId/agents/paused/'
    | '/$companyId/approvals/$approvalId/'
    | '/$companyId/approvals/all/'
    | '/$companyId/company/import/'
    | '/$companyId/company/settings/'
    | '/$companyId/dashboard/live/'
    | '/$companyId/goals/$goalId/'
    | '/$companyId/inbox/all/'
    | '/$companyId/inbox/blocked/'
    | '/$companyId/inbox/recent/'
    | '/$companyId/inbox/requests/'
    | '/$companyId/inbox/unread/'
    | '/$companyId/projects/$projectId/'
    | '/$companyId/routines/$routineId/'
    | '/$companyId/tasks/$taskNumber/'
    | '/$companyId/u/$userId/'
    | '/$companyId/agents/$agentId/$tab/'
    | '/$companyId/company/export/$/'
    | '/$companyId/company/settings/$settingsRoutePath/'
    | '/$companyId/company/settings/instance/'
    | '/$companyId/company/settings/invites/'
    | '/$companyId/company/settings/members/'
    | '/$companyId/company/settings/secrets/'
    | '/$companyId/projects/$projectId/budget/'
    | '/$companyId/projects/$projectId/configuration/'
    | '/$companyId/projects/$projectId/plugin-operations/'
    | '/$companyId/projects/$projectId/tasks/'
    | '/$companyId/routines/$routineId/$section/'
    | '/$companyId/agents/$agentId/runs/$runId/'
    | '/$companyId/company/settings/instance/access/'
    | '/$companyId/company/settings/instance/adapters/'
    | '/$companyId/company/settings/instance/plugins/'
    | '/$companyId/company/settings/instance/profile/'
    | '/$companyId/company/settings/instance/plugins/$pluginId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$companyId'
    | '/'
    | '/auth'
    | '/$'
    | '/onboarding'
    | '/cli-auth/$id'
    | '/invite/$token'
    | '/$companyId/activity'
    | '/$companyId/agents'
    | '/$companyId/approvals'
    | '/$companyId/artifacts'
    | '/$companyId/companies'
    | '/$companyId/costs'
    | '/$companyId/dashboard'
    | '/$companyId/decisions'
    | '/$companyId/goals'
    | '/$companyId/inbox'
    | '/$companyId/projects'
    | '/$companyId/routines'
    | '/$companyId/search'
    | '/$companyId/tasks'
    | '/$companyId/timeline'
    | '/$companyId/$pluginRoutePath/$'
    | '/$companyId/agents/$agentId'
    | '/$companyId/agents/error'
    | '/$companyId/agents/idle'
    | '/$companyId/agents/new'
    | '/$companyId/agents/paused'
    | '/$companyId/approvals/$approvalId'
    | '/$companyId/approvals/all'
    | '/$companyId/company/import'
    | '/$companyId/company/settings'
    | '/$companyId/dashboard/live'
    | '/$companyId/goals/$goalId'
    | '/$companyId/inbox/all'
    | '/$companyId/inbox/blocked'
    | '/$companyId/inbox/recent'
    | '/$companyId/inbox/requests'
    | '/$companyId/inbox/unread'
    | '/$companyId/projects/$projectId'
    | '/$companyId/routines/$routineId'
    | '/$companyId/tasks/$taskNumber'
    | '/$companyId/u/$userId'
    | '/$companyId/agents/$agentId/$tab'
    | '/$companyId/company/export/$'
    | '/$companyId/company/settings/$settingsRoutePath'
    | '/$companyId/company/settings/instance'
    | '/$companyId/company/settings/invites'
    | '/$companyId/company/settings/members'
    | '/$companyId/company/settings/secrets'
    | '/$companyId/projects/$projectId/budget'
    | '/$companyId/projects/$projectId/configuration'
    | '/$companyId/projects/$projectId/plugin-operations'
    | '/$companyId/projects/$projectId/tasks'
    | '/$companyId/routines/$routineId/$section'
    | '/$companyId/agents/$agentId/runs/$runId'
    | '/$companyId/company/settings/instance/access'
    | '/$companyId/company/settings/instance/adapters'
    | '/$companyId/company/settings/instance/plugins'
    | '/$companyId/company/settings/instance/profile'
    | '/$companyId/company/settings/instance/plugins/$pluginId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/$companyId'
    | '/_authenticated/'
    | '/auth/'
    | '/_authenticated/$/'
    | '/_authenticated/onboarding/'
    | '/cli-auth/$id/'
    | '/invite/$token/'
    | '/_authenticated/$companyId/activity/'
    | '/_authenticated/$companyId/agents/'
    | '/_authenticated/$companyId/approvals/'
    | '/_authenticated/$companyId/artifacts/'
    | '/_authenticated/$companyId/companies/'
    | '/_authenticated/$companyId/costs/'
    | '/_authenticated/$companyId/dashboard/'
    | '/_authenticated/$companyId/decisions/'
    | '/_authenticated/$companyId/goals/'
    | '/_authenticated/$companyId/inbox/'
    | '/_authenticated/$companyId/projects/'
    | '/_authenticated/$companyId/routines/'
    | '/_authenticated/$companyId/search/'
    | '/_authenticated/$companyId/tasks/'
    | '/_authenticated/$companyId/timeline/'
    | '/_authenticated/$companyId/$pluginRoutePath/$/'
    | '/_authenticated/$companyId/agents/$agentId/'
    | '/_authenticated/$companyId/agents/error/'
    | '/_authenticated/$companyId/agents/idle/'
    | '/_authenticated/$companyId/agents/new/'
    | '/_authenticated/$companyId/agents/paused/'
    | '/_authenticated/$companyId/approvals/$approvalId/'
    | '/_authenticated/$companyId/approvals/all/'
    | '/_authenticated/$companyId/company/import/'
    | '/_authenticated/$companyId/company/settings/'
    | '/_authenticated/$companyId/dashboard/live/'
    | '/_authenticated/$companyId/goals/$goalId/'
    | '/_authenticated/$companyId/inbox/all/'
    | '/_authenticated/$companyId/inbox/blocked/'
    | '/_authenticated/$companyId/inbox/recent/'
    | '/_authenticated/$companyId/inbox/requests/'
    | '/_authenticated/$companyId/inbox/unread/'
    | '/_authenticated/$companyId/projects/$projectId/'
    | '/_authenticated/$companyId/routines/$routineId/'
    | '/_authenticated/$companyId/tasks/$taskNumber/'
    | '/_authenticated/$companyId/u/$userId/'
    | '/_authenticated/$companyId/agents/$agentId/$tab/'
    | '/_authenticated/$companyId/company/export/$/'
    | '/_authenticated/$companyId/company/settings/$settingsRoutePath/'
    | '/_authenticated/$companyId/company/settings/instance/'
    | '/_authenticated/$companyId/company/settings/invites/'
    | '/_authenticated/$companyId/company/settings/members/'
    | '/_authenticated/$companyId/company/settings/secrets/'
    | '/_authenticated/$companyId/projects/$projectId/budget/'
    | '/_authenticated/$companyId/projects/$projectId/configuration/'
    | '/_authenticated/$companyId/projects/$projectId/plugin-operations/'
    | '/_authenticated/$companyId/projects/$projectId/tasks/'
    | '/_authenticated/$companyId/routines/$routineId/$section/'
    | '/_authenticated/$companyId/agents/$agentId/runs/$runId/'
    | '/_authenticated/$companyId/company/settings/instance/access/'
    | '/_authenticated/$companyId/company/settings/instance/adapters/'
    | '/_authenticated/$companyId/company/settings/instance/plugins/'
    | '/_authenticated/$companyId/company/settings/instance/profile/'
    | '/_authenticated/$companyId/company/settings/instance/plugins/$pluginId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  CliAuthIdIndexRoute: typeof CliAuthIdIndexRoute
  InviteTokenIndexRoute: typeof InviteTokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$companyId': {
      id: '/_authenticated/$companyId'
      path: '/$companyId'
      fullPath: '/$companyId'
      preLoaderRoute: typeof AuthenticatedCompanyIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$/': {
      id: '/_authenticated/$/'
      path: '/$'
      fullPath: '/$/'
      preLoaderRoute: typeof AuthenticatedSplatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/cli-auth/$id/': {
      id: '/cli-auth/$id/'
      path: '/cli-auth/$id'
      fullPath: '/cli-auth/$id/'
      preLoaderRoute: typeof CliAuthIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token/': {
      id: '/invite/$token/'
      path: '/invite/$token'
      fullPath: '/invite/$token/'
      preLoaderRoute: typeof InviteTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$companyId/activity/': {
      id: '/_authenticated/$companyId/activity/'
      path: '/activity'
      fullPath: '/$companyId/activity/'
      preLoaderRoute: typeof AuthenticatedCompanyIdActivityIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/agents/': {
      id: '/_authenticated/$companyId/agents/'
      path: '/agents'
      fullPath: '/$companyId/agents/'
      preLoaderRoute: typeof AuthenticatedCompanyIdAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/approvals/': {
      id: '/_authenticated/$companyId/approvals/'
      path: '/approvals'
      fullPath: '/$companyId/approvals/'
      preLoaderRoute: typeof AuthenticatedCompanyIdApprovalsIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/artifacts/': {
      id: '/_authenticated/$companyId/artifacts/'
      path: '/artifacts'
      fullPath: '/$companyId/artifacts/'
      preLoaderRoute: typeof AuthenticatedCompanyIdArtifactsIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/companies/': {
      id: '/_authenticated/$companyId/companies/'
      path: '/companies'
      fullPath: '/$companyId/companies/'
      preLoaderRoute: typeof AuthenticatedCompanyIdCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/costs/': {
      id: '/_authenticated/$companyId/costs/'
      path: '/costs'
      fullPath: '/$companyId/costs/'
      preLoaderRoute: typeof AuthenticatedCompanyIdCostsIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/dashboard/': {
      id: '/_authenticated/$companyId/dashboard/'
      path: '/dashboard'
      fullPath: '/$companyId/dashboard/'
      preLoaderRoute: typeof AuthenticatedCompanyIdDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/decisions/': {
      id: '/_authenticated/$companyId/decisions/'
      path: '/decisions'
      fullPath: '/$companyId/decisions/'
      preLoaderRoute: typeof AuthenticatedCompanyIdDecisionsIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/goals/': {
      id: '/_authenticated/$companyId/goals/'
      path: '/goals'
      fullPath: '/$companyId/goals/'
      preLoaderRoute: typeof AuthenticatedCompanyIdGoalsIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/inbox/': {
      id: '/_authenticated/$companyId/inbox/'
      path: '/inbox'
      fullPath: '/$companyId/inbox/'
      preLoaderRoute: typeof AuthenticatedCompanyIdInboxIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/projects/': {
      id: '/_authenticated/$companyId/projects/'
      path: '/projects'
      fullPath: '/$companyId/projects/'
      preLoaderRoute: typeof AuthenticatedCompanyIdProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/routines/': {
      id: '/_authenticated/$companyId/routines/'
      path: '/routines'
      fullPath: '/$companyId/routines/'
      preLoaderRoute: typeof AuthenticatedCompanyIdRoutinesIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/search/': {
      id: '/_authenticated/$companyId/search/'
      path: '/search'
      fullPath: '/$companyId/search/'
      preLoaderRoute: typeof AuthenticatedCompanyIdSearchIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/tasks/': {
      id: '/_authenticated/$companyId/tasks/'
      path: '/tasks'
      fullPath: '/$companyId/tasks/'
      preLoaderRoute: typeof AuthenticatedCompanyIdTasksIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/timeline/': {
      id: '/_authenticated/$companyId/timeline/'
      path: '/timeline'
      fullPath: '/$companyId/timeline/'
      preLoaderRoute: typeof AuthenticatedCompanyIdTimelineIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/$pluginRoutePath/$/': {
      id: '/_authenticated/$companyId/$pluginRoutePath/$/'
      path: '/$pluginRoutePath/$'
      fullPath: '/$companyId/$pluginRoutePath/$/'
      preLoaderRoute: typeof AuthenticatedCompanyIdPluginRoutePathSplatIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/agents/$agentId/': {
      id: '/_authenticated/$companyId/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/$companyId/agents/$agentId/'
      preLoaderRoute: typeof AuthenticatedCompanyIdAgentsAgentIdIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/agents/error/': {
      id: '/_authenticated/$companyId/agents/error/'
      path: '/agents/error'
      fullPath: '/$companyId/agents/error/'
      preLoaderRoute: typeof AuthenticatedCompanyIdAgentsErrorIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/agents/idle/': {
      id: '/_authenticated/$companyId/agents/idle/'
      path: '/agents/idle'
      fullPath: '/$companyId/agents/idle/'
      preLoaderRoute: typeof AuthenticatedCompanyIdAgentsIdleIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/agents/new/': {
      id: '/_authenticated/$companyId/agents/new/'
      path: '/agents/new'
      fullPath: '/$companyId/agents/new/'
      preLoaderRoute: typeof AuthenticatedCompanyIdAgentsNewIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/agents/paused/': {
      id: '/_authenticated/$companyId/agents/paused/'
      path: '/agents/paused'
      fullPath: '/$companyId/agents/paused/'
      preLoaderRoute: typeof AuthenticatedCompanyIdAgentsPausedIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/approvals/$approvalId/': {
      id: '/_authenticated/$companyId/approvals/$approvalId/'
      path: '/approvals/$approvalId'
      fullPath: '/$companyId/approvals/$approvalId/'
      preLoaderRoute: typeof AuthenticatedCompanyIdApprovalsApprovalIdIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/approvals/all/': {
      id: '/_authenticated/$companyId/approvals/all/'
      path: '/approvals/all'
      fullPath: '/$companyId/approvals/all/'
      preLoaderRoute: typeof AuthenticatedCompanyIdApprovalsAllIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/company/import/': {
      id: '/_authenticated/$companyId/company/import/'
      path: '/company/import'
      fullPath: '/$companyId/company/import/'
      preLoaderRoute: typeof AuthenticatedCompanyIdCompanyImportIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/company/settings/': {
      id: '/_authenticated/$companyId/company/settings/'
      path: '/company/settings'
      fullPath: '/$companyId/company/settings/'
      preLoaderRoute: typeof AuthenticatedCompanyIdCompanySettingsIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/dashboard/live/': {
      id: '/_authenticated/$companyId/dashboard/live/'
      path: '/dashboard/live'
      fullPath: '/$companyId/dashboard/live/'
      preLoaderRoute: typeof AuthenticatedCompanyIdDashboardLiveIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/goals/$goalId/': {
      id: '/_authenticated/$companyId/goals/$goalId/'
      path: '/goals/$goalId'
      fullPath: '/$companyId/goals/$goalId/'
      preLoaderRoute: typeof AuthenticatedCompanyIdGoalsGoalIdIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/inbox/all/': {
      id: '/_authenticated/$companyId/inbox/all/'
      path: '/inbox/all'
      fullPath: '/$companyId/inbox/all/'
      preLoaderRoute: typeof AuthenticatedCompanyIdInboxAllIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/inbox/blocked/': {
      id: '/_authenticated/$companyId/inbox/blocked/'
      path: '/inbox/blocked'
      fullPath: '/$companyId/inbox/blocked/'
      preLoaderRoute: typeof AuthenticatedCompanyIdInboxBlockedIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/inbox/recent/': {
      id: '/_authenticated/$companyId/inbox/recent/'
      path: '/inbox/recent'
      fullPath: '/$companyId/inbox/recent/'
      preLoaderRoute: typeof AuthenticatedCompanyIdInboxRecentIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/inbox/requests/': {
      id: '/_authenticated/$companyId/inbox/requests/'
      path: '/inbox/requests'
      fullPath: '/$companyId/inbox/requests/'
      preLoaderRoute: typeof AuthenticatedCompanyIdInboxRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/inbox/unread/': {
      id: '/_authenticated/$companyId/inbox/unread/'
      path: '/inbox/unread'
      fullPath: '/$companyId/inbox/unread/'
      preLoaderRoute: typeof AuthenticatedCompanyIdInboxUnreadIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/projects/$projectId/': {
      id: '/_authenticated/$companyId/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/$companyId/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedCompanyIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/routines/$routineId/': {
      id: '/_authenticated/$companyId/routines/$routineId/'
      path: '/routines/$routineId'
      fullPath: '/$companyId/routines/$routineId/'
      preLoaderRoute: typeof AuthenticatedCompanyIdRoutinesRoutineIdIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/tasks/$taskNumber/': {
      id: '/_authenticated/$companyId/tasks/$taskNumber/'
      path: '/tasks/$taskNumber'
      fullPath: '/$companyId/tasks/$taskNumber/'
      preLoaderRoute: typeof AuthenticatedCompanyIdTasksTaskNumberIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/u/$userId/': {
      id: '/_authenticated/$companyId/u/$userId/'
      path: '/u/$userId'
      fullPath: '/$companyId/u/$userId/'
      preLoaderRoute: typeof AuthenticatedCompanyIdUUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/agents/$agentId/$tab/': {
      id: '/_authenticated/$companyId/agents/$agentId/$tab/'
      path: '/agents/$agentId/$tab'
      fullPath: '/$companyId/agents/$agentId/$tab/'
      preLoaderRoute: typeof AuthenticatedCompanyIdAgentsAgentIdTabIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/company/export/$/': {
      id: '/_authenticated/$companyId/company/export/$/'
      path: '/company/export/$'
      fullPath: '/$companyId/company/export/$/'
      preLoaderRoute: typeof AuthenticatedCompanyIdCompanyExportSplatIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/company/settings/$settingsRoutePath/': {
      id: '/_authenticated/$companyId/company/settings/$settingsRoutePath/'
      path: '/company/settings/$settingsRoutePath'
      fullPath: '/$companyId/company/settings/$settingsRoutePath/'
      preLoaderRoute: typeof AuthenticatedCompanyIdCompanySettingsSettingsRoutePathIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/company/settings/instance/': {
      id: '/_authenticated/$companyId/company/settings/instance/'
      path: '/company/settings/instance'
      fullPath: '/$companyId/company/settings/instance/'
      preLoaderRoute: typeof AuthenticatedCompanyIdCompanySettingsInstanceIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/company/settings/invites/': {
      id: '/_authenticated/$companyId/company/settings/invites/'
      path: '/company/settings/invites'
      fullPath: '/$companyId/company/settings/invites/'
      preLoaderRoute: typeof AuthenticatedCompanyIdCompanySettingsInvitesIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/company/settings/members/': {
      id: '/_authenticated/$companyId/company/settings/members/'
      path: '/company/settings/members'
      fullPath: '/$companyId/company/settings/members/'
      preLoaderRoute: typeof AuthenticatedCompanyIdCompanySettingsMembersIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/company/settings/secrets/': {
      id: '/_authenticated/$companyId/company/settings/secrets/'
      path: '/company/settings/secrets'
      fullPath: '/$companyId/company/settings/secrets/'
      preLoaderRoute: typeof AuthenticatedCompanyIdCompanySettingsSecretsIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/projects/$projectId/budget/': {
      id: '/_authenticated/$companyId/projects/$projectId/budget/'
      path: '/projects/$projectId/budget'
      fullPath: '/$companyId/projects/$projectId/budget/'
      preLoaderRoute: typeof AuthenticatedCompanyIdProjectsProjectIdBudgetIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/projects/$projectId/configuration/': {
      id: '/_authenticated/$companyId/projects/$projectId/configuration/'
      path: '/projects/$projectId/configuration'
      fullPath: '/$companyId/projects/$projectId/configuration/'
      preLoaderRoute: typeof AuthenticatedCompanyIdProjectsProjectIdConfigurationIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/projects/$projectId/plugin-operations/': {
      id: '/_authenticated/$companyId/projects/$projectId/plugin-operations/'
      path: '/projects/$projectId/plugin-operations'
      fullPath: '/$companyId/projects/$projectId/plugin-operations/'
      preLoaderRoute: typeof AuthenticatedCompanyIdProjectsProjectIdPluginOperationsIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/projects/$projectId/tasks/': {
      id: '/_authenticated/$companyId/projects/$projectId/tasks/'
      path: '/projects/$projectId/tasks'
      fullPath: '/$companyId/projects/$projectId/tasks/'
      preLoaderRoute: typeof AuthenticatedCompanyIdProjectsProjectIdTasksIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/routines/$routineId/$section/': {
      id: '/_authenticated/$companyId/routines/$routineId/$section/'
      path: '/routines/$routineId/$section'
      fullPath: '/$companyId/routines/$routineId/$section/'
      preLoaderRoute: typeof AuthenticatedCompanyIdRoutinesRoutineIdSectionIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/agents/$agentId/runs/$runId/': {
      id: '/_authenticated/$companyId/agents/$agentId/runs/$runId/'
      path: '/agents/$agentId/runs/$runId'
      fullPath: '/$companyId/agents/$agentId/runs/$runId/'
      preLoaderRoute: typeof AuthenticatedCompanyIdAgentsAgentIdRunsRunIdIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/company/settings/instance/access/': {
      id: '/_authenticated/$companyId/company/settings/instance/access/'
      path: '/company/settings/instance/access'
      fullPath: '/$companyId/company/settings/instance/access/'
      preLoaderRoute: typeof AuthenticatedCompanyIdCompanySettingsInstanceAccessIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/company/settings/instance/adapters/': {
      id: '/_authenticated/$companyId/company/settings/instance/adapters/'
      path: '/company/settings/instance/adapters'
      fullPath: '/$companyId/company/settings/instance/adapters/'
      preLoaderRoute: typeof AuthenticatedCompanyIdCompanySettingsInstanceAdaptersIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/company/settings/instance/plugins/': {
      id: '/_authenticated/$companyId/company/settings/instance/plugins/'
      path: '/company/settings/instance/plugins'
      fullPath: '/$companyId/company/settings/instance/plugins/'
      preLoaderRoute: typeof AuthenticatedCompanyIdCompanySettingsInstancePluginsIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/company/settings/instance/profile/': {
      id: '/_authenticated/$companyId/company/settings/instance/profile/'
      path: '/company/settings/instance/profile'
      fullPath: '/$companyId/company/settings/instance/profile/'
      preLoaderRoute: typeof AuthenticatedCompanyIdCompanySettingsInstanceProfileIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
    '/_authenticated/$companyId/company/settings/instance/plugins/$pluginId/': {
      id: '/_authenticated/$companyId/company/settings/instance/plugins/$pluginId/'
      path: '/company/settings/instance/plugins/$pluginId'
      fullPath: '/$companyId/company/settings/instance/plugins/$pluginId/'
      preLoaderRoute: typeof AuthenticatedCompanyIdCompanySettingsInstancePluginsPluginIdIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyIdRouteRoute
    }
  }
}

interface AuthenticatedCompanyIdRouteRouteChildren {
  AuthenticatedCompanyIdActivityIndexRoute: typeof AuthenticatedCompanyIdActivityIndexRoute
  AuthenticatedCompanyIdAgentsIndexRoute: typeof AuthenticatedCompanyIdAgentsIndexRoute
  AuthenticatedCompanyIdApprovalsIndexRoute: typeof AuthenticatedCompanyIdApprovalsIndexRoute
  AuthenticatedCompanyIdArtifactsIndexRoute: typeof AuthenticatedCompanyIdArtifactsIndexRoute
  AuthenticatedCompanyIdCompaniesIndexRoute: typeof AuthenticatedCompanyIdCompaniesIndexRoute
  AuthenticatedCompanyIdCostsIndexRoute: typeof AuthenticatedCompanyIdCostsIndexRoute
  AuthenticatedCompanyIdDashboardIndexRoute: typeof AuthenticatedCompanyIdDashboardIndexRoute
  AuthenticatedCompanyIdDecisionsIndexRoute: typeof AuthenticatedCompanyIdDecisionsIndexRoute
  AuthenticatedCompanyIdGoalsIndexRoute: typeof AuthenticatedCompanyIdGoalsIndexRoute
  AuthenticatedCompanyIdInboxIndexRoute: typeof AuthenticatedCompanyIdInboxIndexRoute
  AuthenticatedCompanyIdProjectsIndexRoute: typeof AuthenticatedCompanyIdProjectsIndexRoute
  AuthenticatedCompanyIdRoutinesIndexRoute: typeof AuthenticatedCompanyIdRoutinesIndexRoute
  AuthenticatedCompanyIdSearchIndexRoute: typeof AuthenticatedCompanyIdSearchIndexRoute
  AuthenticatedCompanyIdTasksIndexRoute: typeof AuthenticatedCompanyIdTasksIndexRoute
  AuthenticatedCompanyIdTimelineIndexRoute: typeof AuthenticatedCompanyIdTimelineIndexRoute
  AuthenticatedCompanyIdPluginRoutePathSplatIndexRoute: typeof AuthenticatedCompanyIdPluginRoutePathSplatIndexRoute
  AuthenticatedCompanyIdAgentsAgentIdIndexRoute: typeof AuthenticatedCompanyIdAgentsAgentIdIndexRoute
  AuthenticatedCompanyIdAgentsErrorIndexRoute: typeof AuthenticatedCompanyIdAgentsErrorIndexRoute
  AuthenticatedCompanyIdAgentsIdleIndexRoute: typeof AuthenticatedCompanyIdAgentsIdleIndexRoute
  AuthenticatedCompanyIdAgentsNewIndexRoute: typeof AuthenticatedCompanyIdAgentsNewIndexRoute
  AuthenticatedCompanyIdAgentsPausedIndexRoute: typeof AuthenticatedCompanyIdAgentsPausedIndexRoute
  AuthenticatedCompanyIdApprovalsApprovalIdIndexRoute: typeof AuthenticatedCompanyIdApprovalsApprovalIdIndexRoute
  AuthenticatedCompanyIdApprovalsAllIndexRoute: typeof AuthenticatedCompanyIdApprovalsAllIndexRoute
  AuthenticatedCompanyIdCompanyImportIndexRoute: typeof AuthenticatedCompanyIdCompanyImportIndexRoute
  AuthenticatedCompanyIdCompanySettingsIndexRoute: typeof AuthenticatedCompanyIdCompanySettingsIndexRoute
  AuthenticatedCompanyIdDashboardLiveIndexRoute: typeof AuthenticatedCompanyIdDashboardLiveIndexRoute
  AuthenticatedCompanyIdGoalsGoalIdIndexRoute: typeof AuthenticatedCompanyIdGoalsGoalIdIndexRoute
  AuthenticatedCompanyIdInboxAllIndexRoute: typeof AuthenticatedCompanyIdInboxAllIndexRoute
  AuthenticatedCompanyIdInboxBlockedIndexRoute: typeof AuthenticatedCompanyIdInboxBlockedIndexRoute
  AuthenticatedCompanyIdInboxRecentIndexRoute: typeof AuthenticatedCompanyIdInboxRecentIndexRoute
  AuthenticatedCompanyIdInboxRequestsIndexRoute: typeof AuthenticatedCompanyIdInboxRequestsIndexRoute
  AuthenticatedCompanyIdInboxUnreadIndexRoute: typeof AuthenticatedCompanyIdInboxUnreadIndexRoute
  AuthenticatedCompanyIdProjectsProjectIdIndexRoute: typeof AuthenticatedCompanyIdProjectsProjectIdIndexRoute
  AuthenticatedCompanyIdRoutinesRoutineIdIndexRoute: typeof AuthenticatedCompanyIdRoutinesRoutineIdIndexRoute
  AuthenticatedCompanyIdTasksTaskNumberIndexRoute: typeof AuthenticatedCompanyIdTasksTaskNumberIndexRoute
  AuthenticatedCompanyIdUUserIdIndexRoute: typeof AuthenticatedCompanyIdUUserIdIndexRoute
  AuthenticatedCompanyIdAgentsAgentIdTabIndexRoute: typeof AuthenticatedCompanyIdAgentsAgentIdTabIndexRoute
  AuthenticatedCompanyIdCompanyExportSplatIndexRoute: typeof AuthenticatedCompanyIdCompanyExportSplatIndexRoute
  AuthenticatedCompanyIdCompanySettingsSettingsRoutePathIndexRoute: typeof AuthenticatedCompanyIdCompanySettingsSettingsRoutePathIndexRoute
  AuthenticatedCompanyIdCompanySettingsInstanceIndexRoute: typeof AuthenticatedCompanyIdCompanySettingsInstanceIndexRoute
  AuthenticatedCompanyIdCompanySettingsInvitesIndexRoute: typeof AuthenticatedCompanyIdCompanySettingsInvitesIndexRoute
  AuthenticatedCompanyIdCompanySettingsMembersIndexRoute: typeof AuthenticatedCompanyIdCompanySettingsMembersIndexRoute
  AuthenticatedCompanyIdCompanySettingsSecretsIndexRoute: typeof AuthenticatedCompanyIdCompanySettingsSecretsIndexRoute
  AuthenticatedCompanyIdProjectsProjectIdBudgetIndexRoute: typeof AuthenticatedCompanyIdProjectsProjectIdBudgetIndexRoute
  AuthenticatedCompanyIdProjectsProjectIdConfigurationIndexRoute: typeof AuthenticatedCompanyIdProjectsProjectIdConfigurationIndexRoute
  AuthenticatedCompanyIdProjectsProjectIdPluginOperationsIndexRoute: typeof AuthenticatedCompanyIdProjectsProjectIdPluginOperationsIndexRoute
  AuthenticatedCompanyIdProjectsProjectIdTasksIndexRoute: typeof AuthenticatedCompanyIdProjectsProjectIdTasksIndexRoute
  AuthenticatedCompanyIdRoutinesRoutineIdSectionIndexRoute: typeof AuthenticatedCompanyIdRoutinesRoutineIdSectionIndexRoute
  AuthenticatedCompanyIdAgentsAgentIdRunsRunIdIndexRoute: typeof AuthenticatedCompanyIdAgentsAgentIdRunsRunIdIndexRoute
  AuthenticatedCompanyIdCompanySettingsInstanceAccessIndexRoute: typeof AuthenticatedCompanyIdCompanySettingsInstanceAccessIndexRoute
  AuthenticatedCompanyIdCompanySettingsInstanceAdaptersIndexRoute: typeof AuthenticatedCompanyIdCompanySettingsInstanceAdaptersIndexRoute
  AuthenticatedCompanyIdCompanySettingsInstancePluginsIndexRoute: typeof AuthenticatedCompanyIdCompanySettingsInstancePluginsIndexRoute
  AuthenticatedCompanyIdCompanySettingsInstanceProfileIndexRoute: typeof AuthenticatedCompanyIdCompanySettingsInstanceProfileIndexRoute
  AuthenticatedCompanyIdCompanySettingsInstancePluginsPluginIdIndexRoute: typeof AuthenticatedCompanyIdCompanySettingsInstancePluginsPluginIdIndexRoute
}

const AuthenticatedCompanyIdRouteRouteChildren: AuthenticatedCompanyIdRouteRouteChildren =
  {
    AuthenticatedCompanyIdActivityIndexRoute:
      AuthenticatedCompanyIdActivityIndexRoute,
    AuthenticatedCompanyIdAgentsIndexRoute:
      AuthenticatedCompanyIdAgentsIndexRoute,
    AuthenticatedCompanyIdApprovalsIndexRoute:
      AuthenticatedCompanyIdApprovalsIndexRoute,
    AuthenticatedCompanyIdArtifactsIndexRoute:
      AuthenticatedCompanyIdArtifactsIndexRoute,
    AuthenticatedCompanyIdCompaniesIndexRoute:
      AuthenticatedCompanyIdCompaniesIndexRoute,
    AuthenticatedCompanyIdCostsIndexRoute:
      AuthenticatedCompanyIdCostsIndexRoute,
    AuthenticatedCompanyIdDashboardIndexRoute:
      AuthenticatedCompanyIdDashboardIndexRoute,
    AuthenticatedCompanyIdDecisionsIndexRoute:
      AuthenticatedCompanyIdDecisionsIndexRoute,
    AuthenticatedCompanyIdGoalsIndexRoute:
      AuthenticatedCompanyIdGoalsIndexRoute,
    AuthenticatedCompanyIdInboxIndexRoute:
      AuthenticatedCompanyIdInboxIndexRoute,
    AuthenticatedCompanyIdProjectsIndexRoute:
      AuthenticatedCompanyIdProjectsIndexRoute,
    AuthenticatedCompanyIdRoutinesIndexRoute:
      AuthenticatedCompanyIdRoutinesIndexRoute,
    AuthenticatedCompanyIdSearchIndexRoute:
      AuthenticatedCompanyIdSearchIndexRoute,
    AuthenticatedCompanyIdTasksIndexRoute:
      AuthenticatedCompanyIdTasksIndexRoute,
    AuthenticatedCompanyIdTimelineIndexRoute:
      AuthenticatedCompanyIdTimelineIndexRoute,
    AuthenticatedCompanyIdPluginRoutePathSplatIndexRoute:
      AuthenticatedCompanyIdPluginRoutePathSplatIndexRoute,
    AuthenticatedCompanyIdAgentsAgentIdIndexRoute:
      AuthenticatedCompanyIdAgentsAgentIdIndexRoute,
    AuthenticatedCompanyIdAgentsErrorIndexRoute:
      AuthenticatedCompanyIdAgentsErrorIndexRoute,
    AuthenticatedCompanyIdAgentsIdleIndexRoute:
      AuthenticatedCompanyIdAgentsIdleIndexRoute,
    AuthenticatedCompanyIdAgentsNewIndexRoute:
      AuthenticatedCompanyIdAgentsNewIndexRoute,
    AuthenticatedCompanyIdAgentsPausedIndexRoute:
      AuthenticatedCompanyIdAgentsPausedIndexRoute,
    AuthenticatedCompanyIdApprovalsApprovalIdIndexRoute:
      AuthenticatedCompanyIdApprovalsApprovalIdIndexRoute,
    AuthenticatedCompanyIdApprovalsAllIndexRoute:
      AuthenticatedCompanyIdApprovalsAllIndexRoute,
    AuthenticatedCompanyIdCompanyImportIndexRoute:
      AuthenticatedCompanyIdCompanyImportIndexRoute,
    AuthenticatedCompanyIdCompanySettingsIndexRoute:
      AuthenticatedCompanyIdCompanySettingsIndexRoute,
    AuthenticatedCompanyIdDashboardLiveIndexRoute:
      AuthenticatedCompanyIdDashboardLiveIndexRoute,
    AuthenticatedCompanyIdGoalsGoalIdIndexRoute:
      AuthenticatedCompanyIdGoalsGoalIdIndexRoute,
    AuthenticatedCompanyIdInboxAllIndexRoute:
      AuthenticatedCompanyIdInboxAllIndexRoute,
    AuthenticatedCompanyIdInboxBlockedIndexRoute:
      AuthenticatedCompanyIdInboxBlockedIndexRoute,
    AuthenticatedCompanyIdInboxRecentIndexRoute:
      AuthenticatedCompanyIdInboxRecentIndexRoute,
    AuthenticatedCompanyIdInboxRequestsIndexRoute:
      AuthenticatedCompanyIdInboxRequestsIndexRoute,
    AuthenticatedCompanyIdInboxUnreadIndexRoute:
      AuthenticatedCompanyIdInboxUnreadIndexRoute,
    AuthenticatedCompanyIdProjectsProjectIdIndexRoute:
      AuthenticatedCompanyIdProjectsProjectIdIndexRoute,
    AuthenticatedCompanyIdRoutinesRoutineIdIndexRoute:
      AuthenticatedCompanyIdRoutinesRoutineIdIndexRoute,
    AuthenticatedCompanyIdTasksTaskNumberIndexRoute:
      AuthenticatedCompanyIdTasksTaskNumberIndexRoute,
    AuthenticatedCompanyIdUUserIdIndexRoute:
      AuthenticatedCompanyIdUUserIdIndexRoute,
    AuthenticatedCompanyIdAgentsAgentIdTabIndexRoute:
      AuthenticatedCompanyIdAgentsAgentIdTabIndexRoute,
    AuthenticatedCompanyIdCompanyExportSplatIndexRoute:
      AuthenticatedCompanyIdCompanyExportSplatIndexRoute,
    AuthenticatedCompanyIdCompanySettingsSettingsRoutePathIndexRoute:
      AuthenticatedCompanyIdCompanySettingsSettingsRoutePathIndexRoute,
    AuthenticatedCompanyIdCompanySettingsInstanceIndexRoute:
      AuthenticatedCompanyIdCompanySettingsInstanceIndexRoute,
    AuthenticatedCompanyIdCompanySettingsInvitesIndexRoute:
      AuthenticatedCompanyIdCompanySettingsInvitesIndexRoute,
    AuthenticatedCompanyIdCompanySettingsMembersIndexRoute:
      AuthenticatedCompanyIdCompanySettingsMembersIndexRoute,
    AuthenticatedCompanyIdCompanySettingsSecretsIndexRoute:
      AuthenticatedCompanyIdCompanySettingsSecretsIndexRoute,
    AuthenticatedCompanyIdProjectsProjectIdBudgetIndexRoute:
      AuthenticatedCompanyIdProjectsProjectIdBudgetIndexRoute,
    AuthenticatedCompanyIdProjectsProjectIdConfigurationIndexRoute:
      AuthenticatedCompanyIdProjectsProjectIdConfigurationIndexRoute,
    AuthenticatedCompanyIdProjectsProjectIdPluginOperationsIndexRoute:
      AuthenticatedCompanyIdProjectsProjectIdPluginOperationsIndexRoute,
    AuthenticatedCompanyIdProjectsProjectIdTasksIndexRoute:
      AuthenticatedCompanyIdProjectsProjectIdTasksIndexRoute,
    AuthenticatedCompanyIdRoutinesRoutineIdSectionIndexRoute:
      AuthenticatedCompanyIdRoutinesRoutineIdSectionIndexRoute,
    AuthenticatedCompanyIdAgentsAgentIdRunsRunIdIndexRoute:
      AuthenticatedCompanyIdAgentsAgentIdRunsRunIdIndexRoute,
    AuthenticatedCompanyIdCompanySettingsInstanceAccessIndexRoute:
      AuthenticatedCompanyIdCompanySettingsInstanceAccessIndexRoute,
    AuthenticatedCompanyIdCompanySettingsInstanceAdaptersIndexRoute:
      AuthenticatedCompanyIdCompanySettingsInstanceAdaptersIndexRoute,
    AuthenticatedCompanyIdCompanySettingsInstancePluginsIndexRoute:
      AuthenticatedCompanyIdCompanySettingsInstancePluginsIndexRoute,
    AuthenticatedCompanyIdCompanySettingsInstanceProfileIndexRoute:
      AuthenticatedCompanyIdCompanySettingsInstanceProfileIndexRoute,
    AuthenticatedCompanyIdCompanySettingsInstancePluginsPluginIdIndexRoute:
      AuthenticatedCompanyIdCompanySettingsInstancePluginsPluginIdIndexRoute,
  }

const AuthenticatedCompanyIdRouteRouteWithChildren =
  AuthenticatedCompanyIdRouteRoute._addFileChildren(
    AuthenticatedCompanyIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCompanyIdRouteRoute: typeof AuthenticatedCompanyIdRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSplatIndexRoute: typeof AuthenticatedSplatIndexRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCompanyIdRouteRoute:
    AuthenticatedCompanyIdRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSplatIndexRoute: AuthenticatedSplatIndexRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  CliAuthIdIndexRoute: CliAuthIdIndexRoute,
  InviteTokenIndexRoute: InviteTokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
