import type { AcpSubprocessAdapterDefinition } from "@paperclipai/adapter-utils";
import type { AdapterImplementationIdentity } from "@paperclipai/shared";

/** A test-only ACPX discovery result; production never reads this fixture. */
export const CANONICAL_TEST_ADAPTER_TYPE = "fixture-agent";

export const CANONICAL_TEST_ADAPTER_IMPLEMENTATION_IDENTITY: AdapterImplementationIdentity =
  Object.freeze({
    adapterType: CANONICAL_TEST_ADAPTER_TYPE,
    definitionVersion: "acpx-runtime/v1",
    protocolVersion: 1,
    origin: "builtin",
    packageName: "acpx",
    packageVersion: "test-runtime",
    buildIdentity: `acpx-test-runtime:${CANONICAL_TEST_ADAPTER_TYPE}`,
    artifactDigest: "a".repeat(64),
  });

export const CANONICAL_TEST_ADAPTER_DEFINITION: AcpSubprocessAdapterDefinition =
  Object.freeze({
    version: "acpx-runtime/v1",
    launchProfile: Object.freeze({
      registryName: CANONICAL_TEST_ADAPTER_TYPE,
    }),
    environment: Object.freeze({
      cwd: "execution-workspace",
      additionalDirectories: "authorized-workspace-only",
      environmentKeys: Object.freeze([]),
    }),
    runtime: Object.freeze({
      controls: Object.freeze(["session/status", "session/set_config_option"]),
    }),
    ui: Object.freeze({
      label: "Fixture agent",
      description: "Test-only ACPX discovery fixture.",
    }),
    configSchema: Object.freeze({
      fields: Object.freeze([
        Object.freeze({
          key: "model",
          label: "Model",
          type: "select" as const,
          options: Object.freeze([
            Object.freeze({ label: "Fixture model", value: "fixture-model" }),
          ]),
          required: true,
        }),
      ]),
    }),
    configOptions: Object.freeze([
      Object.freeze({
        id: "model",
        configKey: "model",
        label: "Model",
        required: true as const,
        values: Object.freeze([
          Object.freeze({ label: "Fixture model", value: "fixture-model" }),
        ]),
      }),
    ]),
    modelConfigOptionId: "model",
    models: Object.freeze([
      Object.freeze({
        id: "fixture-model",
        label: "Fixture model",
        value: "fixture-model",
        limits: null,
      }),
    ]),
    modelProfiles: Object.freeze([]),
    configurationDoc: "Generated by an ACPX test fixture.",
  });

export function canonicalTestAdapterConfig() {
  return { model: "fixture-model" };
}
