import { unprocessable } from "../errors.js";

import * as policyState from "./task-execution-policy-part-1.js";
import * as policyRules from "./task-execution-policy-part-2.js";

export function applyTaskExecutionStageTransition(
  input: policyState.TransitionInput,
): policyState.TransitionResult {
  const patch: Record<string, unknown> = {};
  const existingState = policyRules.parseTaskExecutionState(input.task.executionState);
  const currentOwner = policyRules.ownerPrincipal(input.task);
  const actor = policyRules.actorPrincipal(input.actor);
  const currentStage = input.policy
    ? policyRules.findStageById(input.policy, existingState?.currentStageId)
    : null;
  const requestedStatus = input.requestedStatus;
  const activeStage =
    currentStage && existingState?.status === policyState.PENDING_STATUS ? currentStage : null;
  const effectiveReviewRequest =
    input.reviewRequest === undefined ? (existingState?.reviewRequest ?? null) : input.reviewRequest;

  if (!input.policy) {
    if (existingState) {
      patch.executionState = null;
      if (input.task.boardPresentationStatus === "in_review" && existingState.returnOwner) {
        patch.status = "in_progress";
      }
    }
    return { patch };
  }

  if (
    (input.task.boardPresentationStatus === "done" || input.task.boardPresentationStatus === "cancelled") &&
    requestedStatus &&
    requestedStatus !== "done" &&
    requestedStatus !== "cancelled"
  ) {
    patch.executionState = null;
    return { patch };
  }

  if (existingState?.currentStageId && !currentStage) {
    policyRules.clearExecutionStatePatch({
      patch,
      taskStatus: input.task.boardPresentationStatus,
      requestedStatus,
      returnOwner: existingState.returnOwner,
    });
    return { patch };
  }

  if (activeStage) {
    const currentParticipant =
      existingState?.currentParticipant ??
      policyRules.selectStageParticipant(activeStage, {
        exclude: existingState?.returnOwner ?? null,
      });
    if (!currentParticipant) {
      throw unprocessable(`No eligible ${activeStage.type} participant is configured for this task`);
    }

    if (!policyRules.stageHasParticipant(activeStage, currentParticipant)) {
      const participant = policyRules.selectStageParticipant(activeStage, {
        preferred: existingState?.currentParticipant ?? null,
        exclude: existingState?.returnOwner ?? null,
      });
      if (!participant) {
        policyRules.clearExecutionStatePatch({
          patch,
          taskStatus: input.task.boardPresentationStatus,
          requestedStatus,
          returnOwner: existingState?.returnOwner ?? null,
        });
        return { patch };
      }

      policyRules.buildPendingStagePatch({
        patch,
        previous: existingState,
        policy: input.policy,
        stage: activeStage,
        participant,
        returnOwner: existingState?.returnOwner ?? currentOwner ?? actor,
        reviewRequest: effectiveReviewRequest,
      });
      return { patch };
    }

    if (policyRules.principalsEqual(currentParticipant, actor)) {
      if (requestedStatus === "done") {
        if (!input.commentBody?.trim()) {
          throw unprocessable("Approving a review or approval stage requires a comment");
        }
        const approvedState = policyRules.buildCompletedState(existingState, activeStage);
        // Only stages after the stage being approved are advance candidates.
        // Scanning the whole policy could wrap back to the first stage when
        // earlier completedStageIds no longer match the policy (e.g. stage ids
        // were regenerated by a mid-flow policy edit), turning a final-stage
        // approval into an endless re-review loop (#7893).
        const nextStage = policyRules.nextPendingStageAfter(input.policy, activeStage, approvedState);

        if (!nextStage) {
          patch.executionState = approvedState;
          return {
            patch,
            decision: {
              stageId: activeStage.id,
              stageType: activeStage.type,
              outcome: "approved",
              body: input.commentBody.trim(),
            },
          };
        }

        const participant = policyRules.selectStageParticipant(nextStage, {
          exclude: existingState?.returnOwner ?? null,
        });
        if (!participant) {
          throw unprocessable(`No eligible ${nextStage.type} participant is configured for this task`);
        }

        policyRules.buildPendingStagePatch({
          patch,
          previous: approvedState,
          policy: input.policy,
          stage: nextStage,
          participant,
          returnOwner: existingState?.returnOwner ?? currentOwner ?? actor,
          reviewRequest: input.reviewRequest ?? null,
        });
        return {
          patch,
          decision: {
            stageId: activeStage.id,
            stageType: activeStage.type,
            outcome: "approved",
            body: input.commentBody.trim(),
          },
        };
      }

      if (requestedStatus && requestedStatus !== "in_review") {
        if (!input.commentBody?.trim()) {
          throw unprocessable("Requesting changes requires a comment");
        }
        if (!existingState?.returnOwner) {
          throw unprocessable("This execution stage has no return owner");
        }
        patch.status = "in_progress";
        patch.executionState = policyRules.buildChangesRequestedState(existingState, activeStage);
        return {
          patch,
          decision: {
            stageId: activeStage.id,
            stageType: activeStage.type,
            outcome: "changes_requested",
            body: input.commentBody.trim(),
          },
        };
      }
    }

    const attemptedStageAdvance = requestedStatus !== undefined && requestedStatus !== "in_review";
    const stageStateDrifted =
      input.task.boardPresentationStatus !== "in_review" ||
      !policyRules.principalsEqual(existingState?.currentParticipant ?? null, currentParticipant);

    if (attemptedStageAdvance && !stageStateDrifted) {
      throw unprocessable("Only the active reviewer or approver can advance the current execution stage");
    }

    if (stageStateDrifted) {
      policyRules.buildPendingStagePatch({
        patch,
        previous: existingState,
        policy: input.policy,
        stage: activeStage,
        participant: currentParticipant,
        returnOwner: existingState?.returnOwner ?? currentOwner ?? actor,
        reviewRequest: effectiveReviewRequest,
      });
      return { patch };
    }

    return { patch };
  }

  const shouldStartWorkflow = requestedStatus === "done" || requestedStatus === "in_review";

  if (!shouldStartWorkflow) {
    return { patch };
  }

  // A workflow whose execution already completed is terminal for approve/done:
  // closing the task must not restart the chain at the first stage (#7893).
  if (requestedStatus === "done" && existingState?.status === policyState.COMPLETED_STATUS) {
    return { patch };
  }

  let pendingStage =
    existingState?.status === policyState.CHANGES_REQUESTED_STATUS && currentStage
      ? currentStage
      : policyRules.nextPendingStage(input.policy, existingState);
  if (!pendingStage) return { patch };

  const returnOwner = existingState?.returnOwner ?? currentOwner;
  const skippedStageIds = [...(existingState?.completedStageIds ?? [])];
  let participant = policyRules.selectStageParticipant(pendingStage, {
    preferred:
      existingState?.status === policyState.CHANGES_REQUESTED_STATUS
        ? (existingState.currentParticipant ?? null)
        : null,
    exclude: returnOwner,
  });
  while (
    !participant &&
    policyRules.canAutoSkipPendingStage({
      stage: pendingStage,
      returnOwner,
      requestedStatus,
    })
  ) {
    skippedStageIds.push(pendingStage.id);
    pendingStage = policyRules.nextPendingStage(
      input.policy,
      policyRules.buildStateWithCompletedStages({
        previous: existingState,
        completedStageIds: skippedStageIds,
        returnOwner,
      }),
    );
    if (!pendingStage) {
      patch.executionState = policyRules.buildSkippedStageCompletedState({
        previous: existingState,
        completedStageIds: skippedStageIds,
        returnOwner,
      });
      return { patch };
    }
    participant = policyRules.selectStageParticipant(pendingStage, {
      preferred:
        existingState?.status === policyState.CHANGES_REQUESTED_STATUS
          ? (existingState.currentParticipant ?? null)
          : null,
      exclude: returnOwner,
    });
  }
  if (!participant) {
    throw unprocessable(`No eligible ${pendingStage.type} participant is configured for this task`);
  }

  policyRules.buildPendingStagePatch({
    patch,
    previous:
      skippedStageIds.length === (existingState?.completedStageIds ?? []).length
        ? existingState
        : policyRules.buildStateWithCompletedStages({
            previous: existingState,
            completedStageIds: skippedStageIds,
            returnOwner,
          }),
    policy: input.policy,
    stage: pendingStage,
    participant,
    returnOwner,
    reviewRequest: input.reviewRequest ?? null,
  });
  return { patch };
}

export function applyMonitorTransition(
  input: policyState.TransitionInput,
  stagePatch: Record<string, unknown>,
) {
  const patch: Record<string, unknown> = {};
  const previousPolicy =
    input.previousPolicy ?? policyRules.normalizeTaskExecutionPolicy(input.task.executionPolicy ?? null);
  const existingState = policyRules.parseTaskExecutionState(input.task.executionState);
  const currentMonitorState = policyState.derivePersistedMonitorState({
    task: input.task,
    state: existingState,
    policy: previousPolicy,
  });
  const nextStatus =
    typeof stagePatch.status === "string"
      ? (stagePatch.status as string)
      : (input.requestedStatus ?? input.task.boardPresentationStatus);
  const { ownerKind, ownerAgentId, ownerUserId } = policyState.nextOwner({
    task: input.task,
    requestedOwnerPatch: input.requestedOwnerPatch,
  });
  const stageState =
    stagePatch.executionState !== undefined
      ? policyRules.parseTaskExecutionState(stagePatch.executionState)
      : existingState;
  const invalidReason = input.policy?.monitor
    ? policyState.monitorClearReasonForTask(nextStatus, ownerKind, ownerAgentId, ownerUserId)
    : null;

  let targetMonitorState = currentMonitorState;

  if (input.policy?.monitor) {
    if (invalidReason) {
      if (input.monitorExplicitlyUpdated) {
        throw unprocessable(policyState.MONITOR_INVALID_MESSAGE);
      }
      patch.executionPolicy = policyState.stripMonitorFromExecutionPolicy(input.policy);
      patch.monitorNextCheckAt = null;
      targetMonitorState = policyState.buildClearedMonitorState({
        previous: currentMonitorState,
        clearReason: invalidReason,
        clearedAt: new Date(),
      });
    } else {
      const exhaustedReason = policyState.exhaustedMonitorClearReason({
        monitor: input.policy.monitor,
        attemptCount: currentMonitorState?.attemptCount ?? 0,
        now: new Date(),
      });
      if (exhaustedReason) {
        if (input.monitorExplicitlyUpdated) {
          throw unprocessable(policyState.MONITOR_BOUNDS_EXHAUSTED_MESSAGE, {
            clearReason: exhaustedReason,
          });
        }
        patch.executionPolicy = policyState.stripMonitorFromExecutionPolicy(input.policy);
        patch.monitorNextCheckAt = null;
        targetMonitorState = policyState.buildClearedMonitorState({
          previous: currentMonitorState,
          clearReason: exhaustedReason,
          clearedAt: new Date(),
        });
      } else {
        patch.monitorNextCheckAt = new Date(input.policy.monitor.nextCheckAt);
        patch.monitorNotes = input.policy.monitor.notes ?? null;
        patch.monitorScheduledBy = input.policy.monitor.scheduledBy;
        targetMonitorState = policyState.buildScheduledMonitorState(
          currentMonitorState,
          input.policy.monitor,
        );
      }
    }
  } else if (previousPolicy?.monitor) {
    patch.monitorNextCheckAt = null;
    targetMonitorState = policyState.buildClearedMonitorState({
      previous: currentMonitorState,
      clearReason: input.monitorExplicitlyUpdated
        ? "manual"
        : (policyState.monitorClearReasonForTask(nextStatus, ownerKind, ownerAgentId, ownerUserId) ??
          "manual"),
      clearedAt: new Date(),
    });
  }

  if (
    stagePatch.executionState !== undefined ||
    !policyState.monitorStatesEqual(currentMonitorState, targetMonitorState)
  ) {
    patch.executionState = policyState.executionStateWithMonitor(stageState, targetMonitorState);
  }

  return patch;
}

export function applyTaskExecutionPolicyTransition(
  input: policyState.TransitionInput,
): policyState.TransitionResult {
  const stageResult = applyTaskExecutionStageTransition(input);
  const monitorPatch = applyMonitorTransition(input, stageResult.patch);
  Object.assign(stageResult.patch, monitorPatch);
  return stageResult;
}

export type TaskExecutionPolicyActor = {
  agentId?: string | null;
  userId?: string | null;
  runId?: string | null;
};
